### ISSUE TITLE
Issues with Home Assistant 2022.10.4 and 1.0.1

### ISSUE THREAD

**Issue by smackie** [bmcclure/ha-aquanta#2]
Hi! Just installed an Aquanta into an existing HA installation and I'm seeing a few sensor issues. The plug-in is basically working but the sensors don't seem to have the right units or marked as measurements.

The main issue is that the "Current Temperature" sensor doesn't appear to have units - when I look at it in the Developer Tools, all it has is the name info - it's not marked as a measurement or that the units are Centigrade. Same problem for the hot water percentage.

Any thoughts on this? I did stare at the code in comparison with other plugins and just wondering if there have been newer changes to the HA interface that have broken something?

Cheers!

Scott... 

![Screen Shot 2022-10-17 at 14 22 50](https://user-images.githubusercontent.com/440187/196286170-3f63ebee-4cfe-4277-af50-4c8ce83179a4.jpg)

**Comment by bmcclure** [comment]
Thanks for this report, and sorry that it took me months to get back to you! I plan to make a new release of this integration soon and will make sure to figure out this issue with using the proper units.

**Comment by bmcclure** [comment]
These items should be fixed now in v2.0. Let me know if you have any further issues!

**Comment by smackie** [comment]
Looks great, Ben! Thanks very much for fixing this!
