### ISSUE TITLE
Invalid Handler Specified

### ISSUE THREAD

**Issue by Mark612** [bmcclure/ha-aquanta#27]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bmcclure/ha-aquanta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I had a previous custom_integration 'aquanta' (never installed in HACS), before trying to install this new aquanta through HACS. 

Running Home Assistant 2023.4.6, in docker.

When I add the integration, last step, it fails:

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

### Reproduction steps

1. Removed old custom_integration 'aquanta' directory (another repository and version of this program)
2. Restarted home assistant
3. Added this new repository to HACS, and downloaded
4. Restarted home assistant. It now shows up in HACS properly.
5. Went to settings, integrations and added Aquanta.

Get the error.

### Debug logs

```Text
N/A
```

**Comment by Mark612** [comment]
Looks like it is a python [bug](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/277), similar users are finding in home assistant.

**Comment by Mark612** [comment]
The old aquanta custom integration I had installed was from another source.

And, I did clean out all the .storage files with any water_heater or aquanta names. Now left with this:

>> sudo grep -i aquanta

hacs.repositories:        "name": "Aquanta",
hacs.repositories:        "filename": "aquanta.zip",
hacs.repositories:      "full_name": "bmcclure/ha-aquanta",
hacs.repositories:      "description": "An unofficial Aquanta water heater controller integration for Home Assistant",
hacs.repositories:      "domain": "aquanta",
hacs.repositories:      "manifest_name": "Aquanta",


From the logs:

2023-05-12 07:23:57.893 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration aquanta: cannot import name 'Aquanta' from 'aquanta' (/config/aquanta/__init__.py)
2023-05-12 07:23:58.451 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

**Comment by bmcclure** [comment]
The error about not being able to import Aquanta from aquanta makes me wonder if there is a naming conflict. The custom integration is called `aquanta`, and the underlying python lib that it uses is also called `aquanta`.

In my IDE, it sometimes gives me a warning to the effect of not being able to find the Aquanta class, because it's looking in my custom integration instead of in the aquanta library. I always thought it was just an issue with how my IDE is parsing things, since it works fine for me in Home Assistant as-is, however I wonder if there's any chance that could be related.

**Comment by Mark612** [comment]
> The error about not being able to import Aquanta from aquanta makes me wonder if there is a naming conflict. The custom integration is called `aquanta`, and the underlying python lib that it uses is also called `aquanta`.

I think you are on to something. I upgraded my home assistant to 2023.5.2. It went through the sequence again of setting things up (so appeared to be working), then gave me the error.

We could try another name, a beta version, aquantaio maybe.

**Comment by bmcclure** [comment]
I've been reading in a few other issues (such as [this one](https://community.home-assistant.io/t/custom-python-library-name-collision/298160/8)) and it seems like it should be fine to have a python library with the same name as an integration. Apparently it works like that on some core integrations too, such as broadlink.

But I would be willing to make a branch that uses a different name as a test still, to at least rule it out if nothing else.

In your logs, do you always see that HTTP failure immediately after the aquanta error?

**Comment by Mark612** [comment]
I'm getting the "Invalid method encountered" error a lot, most likely from something else. It occurs independently of adding the aquanta integration.

See the log below, about 8 seconds since I tried adding it. So, most likely this second error is not related.

2023-05-12 10:09:20.785 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration aquanta: cannot import name 'Aquanta' from 'aquanta' (/config/aquanta/__init__.py)
2023-05-12 10:09:28.044 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

**Comment by bmcclure** [comment]
The path in the error seems interesting, /config/aquanta/init.py. Do you actually have a directory named aquanta under /config?

**Comment by Mark612** [comment]
> The path in the error seems interesting, /config/aquanta/init.py. Do you actually have a directory named aquanta under /config?
> 
> That makes me wonder if python is finding another aquanta library at that location instead of the one this integration is trying to use.

Yes! Great catch. I removed that directory and it is now working fine! You solved it.

I had no idea that having a directory with the same name under /config (and under custom_components) would cause this. It seems that HA takes the directory /config/<name> as the priority if there is a duplicate <name> under custom_components.

I'm up and running now. Thank you for all the help! Greatly appreciated.

**Comment by bmcclure** [comment]
Awesome, that's great news! No problem, I'm really glad we figured it out. Keep me posted if you run into any other issues!
