### ISSUE TITLE
Make Temperature units match the default temp unit in HOmeAssistant

### ISSUE THREAD

**Issue by appstatefan01** [bmcclure/ha-aquanta#3]
**Is your feature request related to a problem? Please describe.**
I have my HA set to F and Aquanta shows temp in C.  

**Describe the solution you'd like**
Use the default HA temp units. 

**Describe alternatives you've considered**
I've looked at "https://community.home-assistant.io/t/convert-celsius-to-fahrenheit-in-sensor/271388" but seems like it is best to do it in the integration. 

**Additional context**

**Comment by bmcclure** [comment]
Thanks for the report! It's odd, it seems that maybe the unit of temperature that an Aquanta device provides can potentially be different. I will investigate this further and see if I can get it working right.

**Comment by bmcclure** [comment]
This should be all set now in v2.0!
