### ISSUE TITLE
Failed Setup

### ISSUE THREAD

**Issue by Mark612** [bmcclure/ha-aquanta#56]
## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.15.0-73-generic
arch | x86_64
timezone | America/Denver
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4667
Installed Version | 1.33.0
Stage | running
Available Repositories | 1374
Downloaded Repositories | 39

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 27, 2024 at 5:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-10.ui.nabu.casa
certificate_status | ready
instance_id | xxxxxxx
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 26
views | 41
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 18, 2023 at 4:56 PM
-- | --
current_recorder_run | January 11, 2024 at 5:11 PM
estimated_db_size | 1065.73 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bmcclure/ha-aquanta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Been working for months on the current ha-aquanta version, and got the error 1/11/2024: "Failed setup, will retry". Reloading and restarting does not solve the issue. 

Other code will authenticate and work fine.

Will keep retrying, may be a temporary issue given the randomness of the occurrance. 

> 

### Reproduction steps

1. Restart will fail setup.
2.
3.
...

### Debug logs

```Text
2024-01-11 17:54:28.706 DEBUG (MainThread) [custom_components.aquanta] Finished fetching aquanta data in 0.317 seconds (success: False)
2024-01-11 17:54:35.011 DEBUG (MainThread) [custom_components.aquanta] Finished fetching aquanta data in 0.317 seconds (success: False)

```

**Comment by jpreiditsch** [comment]
Same, it appears to have started yesterday at 5:45PM EST

Failed to GET /v2/devices <Response [401]>

**Comment by joseror** [comment]
Same. The integration has been unavailable since yesterday. Restarting and reloading did not fix it.

**Comment by jeremy-compostella** [comment]
They changed something on the server side. I have fixed this issue with aquanta-0.2. Update your aquanta module.

**Comment by jeremy-compostella** [comment]
https://github.com/bmcclure/ha-aquanta/pull/57 should fix this issue.

**Comment by bmcclure** [comment]
Thanks for the report, and thank you @jeremy-compostella for the PR!

I've haven't experienced this issue yet, so perhaps they are rolling the new API out slowly. But I will make a new release of this integration ASAP so that it will hopefully fix it for those having problems.

**Comment by bmcclure** [comment]
I just release version 2.0.4 of the integration, containing only dependency updates. It sounds like that should resolve this issue, but let me know if it does not!

**Comment by bmcclure** [comment]
I will assume this is resolved with the previous updates. Thanks for the reports and for pointing to the fix!
