### ISSUE TITLE
aquanta_mode value of 'timer'

### ISSUE THREAD

**Issue by Concours99** [bmcclure/ha-aquanta#70]
## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 229.2 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.1.0), Studio Code Server (5.15.0), Home Assistant Google Drive Backup (0.112.1), Tailscale (0.15.0), Mosquitto broker (6.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 5
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 7, 2024 at 12:27 PM
-- | --
current_recorder_run | February 15, 2024 at 10:43 AM
estimated_db_size | 173.29 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bmcclure/ha-aquanta/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Looking through my logs, I see my home assistant struggling with a value of 'timer' from my sensor.aquanta_mode.  Looking at that  entity, I only see values of "Possible states        setpoint, intelligence, boost, away, off"

### Reproduction steps

1.
2.
3.
...

### Debug logs

```Text
2024-02-15 04:04:45.644 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 643, in state
    raise ValueError(
ValueError: Sensor sensor.aquanta_mode provides state value 'timer', which is not in the list of options provided
```

**Comment by bmcclure** [comment]
Thanks for the report, and sorry to have ignored this for so long! I will be making some updates to the aquanta integration soon and will try and ensure this issue is fixed as well.

**Comment by bmcclure** [comment]
This should be fixed now in https://github.com/bmcclure/ha-aquanta/commit/b987aa1242eaa48bc4fddee6314261d62c533876. I'll get a release out shortly that includes this change. Thanks again for the report!

**Comment by bmcclure** [comment]
New release posted, let me know if you run into any further issues with this, but I think it should be safe to close the issue for now.

**Comment by Concours99** [comment]
Thank you.  I'll let you know if there are any issues.

 

Cheers,

Wayne

@***@***.***

 

When you are young, you want to change the world; when you are old, you want
to change the young.
